### ISSUE TITLE
Support of mobile viewport collapsible

### ISSUE THREAD

**Issue by beesarmy** [uxcore/uxcore-menu#4]
Hi, I'm looking for a react component lib for my mobile web app project. I was planning to use My original plan was to use http://react-bootstrap.github.io.  But then I stumbled upon uxcore and it looks great and has a much richer component library.  However I have a couple questions if you guys can help me,

* Is uxcore optimized for mobile: uxcore's github account has this statement "React component lib for PC".
* This menu component doesn't seem to support auto-collapse on mobile device (like http://react-bootstrap.github.io/components.html#navigation). Is that correct? Do you plan to support that?

Thanks a lot!

**Comment by eternalsky** [comment]
Thanks for your appreciation. As you see, UXCore is living for pc and not prepared to support mobile, because we want do the best for each terminal. So pc is for pc, and mobile is for mobile.  Maybe you can try our mobile UI suites named [tinglejs](http://gitlab.alibaba-inc.com/groups/tinglejs).

**Comment by beesarmy** [comment]
@eternalsky Thanks for your quick response.  Is http://gitlab.alibaba-inc.com/groups/tinglejs down or it's Alibaba internal site?

**Comment by eternalsky** [comment]
@beesarmy sorry, correct link is here: https://github.com/tinglejs/

**Comment by beesarmy** [comment]
Thanks a lot @eternalsky !
