### ISSUE TITLE
Support ` text-overflow: ellipsis` when text inside menu item is too long

### ISSUE THREAD

**Issue by SurfaceW** [uxcore/uxcore-menu#7]
And it should support title property on the MenuItem to show tip when hover on the menu item.

![image](https://cloud.githubusercontent.com/assets/5323168/23640717/5a9cb75e-032a-11e7-8ca0-4a888906a3e4.png)

**Comment by eternalsky** [comment]
Showing tip is not menu's business. MenuItem's children can be string or react element, so if you need hover tip or ellipsis, you should do this in MenuItem's children.

**Comment by SurfaceW** [comment]
OK
